spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print

jwt:
  password: CodeStatesPreProject11team
  validTime: 1800000


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1036778914352-hf8n4p5v38vbnjp4koc2biqgqfpupp1o.apps.googleusercontent.com
            client-secret: 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